### ISSUE TITLE
Add molpipeline.__version__

### ISSUE THREAD

**Issue by c-w-feldmann** [basf/MolPipeline#125]
To include `molpipeline.__version__` and have no redundancy with the pyproject.toml I would propose the solution I found [here](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata): 
For our case this would mean:
1)
define `__version__` in molpipeline/__init__.py
2)
change to pyproject.toml to:
```toml
[project]
# ...
dynamic = ["version"]
# ...
[tool.setuptools.dynamic]
version = {attr = "molpipeline.__version__"} 
```
